name: Deploy Laravel to EC2

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Test if Secrets are Available
      - name: Check Secrets Presence
        run: |
          if [ -z "${{ secrets.EC2_HOST }}" ]; then
            echo "::error::EC2_HOST secret is missing!"
          else
            echo "EC2_HOST secret is set."
          fi

          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "::error::SSH_PRIVATE_KEY secret is missing!"
          else
            echo "SSH_PRIVATE_KEY secret is set."
          fi

      # Step 3: SSH into EC2 and deploy code
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}       # Your EC2 instance IP
          username: ubuntu                    # Default username for Ubuntu EC2 instances
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # The private key from GitHub secrets
          script: |
            # Navigate to the project directory
            cd /var/www/cafeteria-api

            # Pull the latest changes from GitHub
            git pull origin main

            # Install PHP dependencies
            composer install --no-dev --prefer-dist --no-progress --no-interaction --optimize-autoloader

            # Run Laravel migrations
            php artisan migrate --force

            # Clear and cache configurations, routes, and views
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # Restart necessary services
            sudo systemctl restart nginx
            sudo systemctl restart php8.3-fpm
